repos:
    - repo: local
      hooks:
        - id: isort
          name: isort
          entry: poetry run isort ./desafio_tikal ./tests
          language: system
          always_run: true
        - id: black
          name: black
          entry: poetry run black ./desafio_tikal ./tests
          language: system
          pass_filenames: false
          always_run: true
        - id: flake8
          name: flake8
          entry: poetry run flake8 ./desafio_tikal ./tests
          language: system
          pass_filenames: false
          always_run: true
