version: "3.9"

services:
  database:
    build: ./docker/database
    ports:
      - 5432:5432
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
  msconsulta:
    build: ./desafio_tikal/msconsulta
    command: poetry run python main.py
  mscrud:
    build: ./desafio_tikal/mscrud
    command: poetry run python manage.py runserver 0.0.0.0:8000
